from pathlib import Path
import os
import streamlit as st
from sqlalchemy import create_engine, text

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

LOCAL_DB_PATH = DATA_DIR / "auction_v5_local.db"


def build_database_url_v5():
    app_cfg = st.secrets.get("app", {})
    force_sqlite = bool(app_cfg.get("force_sqlite", False))
    if force_sqlite:
        return f"sqlite:///{LOCAL_DB_PATH.as_posix()}"

    if "database" in st.secrets:
        db = st.secrets["database"]
        host = str(db.get("host", "")).strip()
        database = str(db.get("database", "")).strip()
        username = str(db.get("username", "")).strip()
        password = str(db.get("password", "")).strip()

        placeholders = {"SEU_HOST", "SEU_BANCO", "SEU_USUARIO", "SUA_SENHA"}
        if host in placeholders or database in placeholders or username in placeholders or password in placeholders:
            raise ValueError("secrets.toml ainda contém valores de exemplo.")

        dialect = db.get("dialect", "postgresql")
        port = str(db.get("port", "5432"))
        sslmode = db.get("sslmode", "require")
        return f"{dialect}+psycopg2://{username}:{password}@{host}:{port}/{database}?sslmode={sslmode}"

    env_url = os.getenv("DATABASE_URL", "").strip()
    if env_url:
        return env_url

    return f"sqlite:///{LOCAL_DB_PATH.as_posix()}"

DATABASE_URL = build_database_url_v5()
IS_POSTGRES = DATABASE_URL.startswith("postgresql")

ENGINE_KWARGS = {
    "future": True,
    "pool_pre_ping": True,
}

if IS_POSTGRES:
    ENGINE_KWARGS.update({
        "pool_timeout": 10,
        "pool_recycle": 1800,
        "connect_args": {
            "connect_timeout": 5,
            "options": "-c statement_timeout=15000 -c lock_timeout=5000"
        }
    })

engine = create_engine(DATABASE_URL, **ENGINE_KWARGS)


def is_postgres_v5():
    return IS_POSTGRES


def healthcheck_db_v5():
    with engine.begin() as conn:
        conn.execute(text("SELECT 1"))


def init_db_v5():
    with engine.begin() as conn:
        if is_postgres_v5():
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS teams (
                    team_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    team_name TEXT UNIQUE NOT NULL,
                    cap_limit DOUBLE PRECISION NOT NULL
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS users (
                    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email TEXT UNIQUE NOT NULL,
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL,
                    team_id INTEGER NULL,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    must_change_password INTEGER NOT NULL DEFAULT 1,
                    FOREIGN KEY(team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS players (
                    player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    player_name TEXT NOT NULL,
                    position TEXT NOT NULL,
                    owner_team_id INTEGER NULL,
                    status TEXT NOT NULL DEFAULT 'OPEN',
                    closed_at TEXT NULL,
                    UNIQUE(player_name, position),
                    FOREIGN KEY(owner_team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS bids (
                    bid_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    player_id INTEGER NOT NULL,
                    team_id INTEGER NOT NULL,
                    amount DOUBLE PRECISION NOT NULL,
                    years INTEGER NOT NULL,
                    created_at TEXT NOT NULL,
                    is_valid INTEGER NOT NULL DEFAULT 1,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    is_renewal INTEGER NOT NULL DEFAULT 0,
                    invalid_reason TEXT NULL,
                    created_by_user_id INTEGER NULL,
                    FOREIGN KEY(player_id) REFERENCES players(player_id),
                    FOREIGN KEY(team_id) REFERENCES teams(team_id),
                    FOREIGN KEY(created_by_user_id) REFERENCES users(user_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS player_state (
                    player_id INTEGER PRIMARY KEY,
                    active_bid_id INTEGER NULL,
                    active_team_id INTEGER NULL,
                    active_amount DOUBLE PRECISION NULL,
                    active_years INTEGER NULL,
                    active_at TEXT NULL,
                    expires_at TEXT NULL,
                    status TEXT NOT NULL DEFAULT 'OPEN',
                    is_renewal INTEGER NOT NULL DEFAULT 0,
                    FOREIGN KEY(player_id) REFERENCES players(player_id),
                    FOREIGN KEY(active_bid_id) REFERENCES bids(bid_id),
                    FOREIGN KEY(active_team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS audit_log (
                    audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_time TEXT NOT NULL,
                    username TEXT NULL,
                    action TEXT NOT NULL,
                    entity_type TEXT NOT NULL,
                    entity_id TEXT NULL,
                    details TEXT NULL
                )
            """))
        else:
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS teams (
                    team_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    team_name TEXT UNIQUE NOT NULL,
                    cap_limit REAL NOT NULL
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS users (
                    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    email TEXT UNIQUE NOT NULL,
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL,
                    team_id INTEGER NULL,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    must_change_password INTEGER NOT NULL DEFAULT 1,
                    FOREIGN KEY(team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS players (
                    player_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    player_name TEXT NOT NULL,
                    position TEXT NOT NULL,
                    owner_team_id INTEGER NULL,
                    status TEXT NOT NULL DEFAULT 'OPEN',
                    closed_at TEXT NULL,
                    UNIQUE(player_name, position),
                    FOREIGN KEY(owner_team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS bids (
                    bid_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    player_id INTEGER NOT NULL,
                    team_id INTEGER NOT NULL,
                    amount REAL NOT NULL,
                    years INTEGER NOT NULL,
                    created_at TEXT NOT NULL,
                    is_valid INTEGER NOT NULL DEFAULT 1,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    is_renewal INTEGER NOT NULL DEFAULT 0,
                    invalid_reason TEXT NULL,
                    created_by_user_id INTEGER NULL,
                    FOREIGN KEY(player_id) REFERENCES players(player_id),
                    FOREIGN KEY(team_id) REFERENCES teams(team_id),
                    FOREIGN KEY(created_by_user_id) REFERENCES users(user_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS player_state (
                    player_id INTEGER PRIMARY KEY,
                    active_bid_id INTEGER NULL,
                    active_team_id INTEGER NULL,
                    active_amount REAL NULL,
                    active_years INTEGER NULL,
                    active_at TEXT NULL,
                    expires_at TEXT NULL,
                    status TEXT NOT NULL DEFAULT 'OPEN',
                    is_renewal INTEGER NOT NULL DEFAULT 0,
                    FOREIGN KEY(player_id) REFERENCES players(player_id),
                    FOREIGN KEY(active_bid_id) REFERENCES bids(bid_id),
                    FOREIGN KEY(active_team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS audit_log (
                    audit_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    event_time TEXT NOT NULL,
                    username TEXT NULL,
                    action TEXT NOT NULL,
                    entity_type TEXT NOT NULL,
                    entity_id TEXT NULL,
                    details TEXT NULL
                )
            """))