[database]
dialect = "postgresql"
host = "ep-wild-credit-acpjkpv8.sa-east-1.aws.neon.tech"
port = "5432"
database = "neondb"
username = "neondb_owner"
password = "npg_XlYDys1E0PgJ"
sslmode = "require"

[app]
environment = "production"
force_sqlite = true
admin_email = "admin@auction.local"
admin_password = "admin123"